currentBuild.displayName = "#${currentBuild.number}-etl-${params.appEnv}"
properties(
  [parameters(
    [
      string(
      defaultValue: 'etl',
      description: 'Name of directory to run',
      name: 'DirName'
      ),
      string(
      description: 'Choose Docker ECR URL to deploy',
      name: 'ecrURL'
      ),
      choice(
      choices: ['dev', 'itg', 'mirroritg', 'mirror', 'prod'],
      description: 'environments', name: 'appEnv')

    ])
  ]
)


pipeline{
  agent any
  stages{
    stage{
      step{
        dir("${DirName}"){
          sh """
          echo "1st build ${DirName}"
          pwd
          """
        }
      }
    }
  }
}
