currentBuild.displayName = "#${currentBuild.number}-etl-${params.appEnv}"
properties(
  [parameters(
    [
      string(
      defaultValue: 'etl/card/',
      description: 'Name of directory to run',
      name: 'DirName'
      ),
      string(
      description: 'Choose Docker ECR URL to deploy',
      name: 'ecrURL'
      ),
      choice(
      choices: ['dev', 'itg', 'mirroritg', 'mirror', 'prod'],
      description: 'environments', name: 'appEnv')

    ])
  ]
)


pipeline{
  agent any
  stages{
    stage("Test"){
      steps{
        dir(params.DirName) {
          sh """
          echo "1st build ${params.DirName}"
          pwd
          """
        }
      }
    }
  }
}
